### ISSUE TITLE
Sonatype Nexus Persistant Volumes

### ISSUE THREAD

**Issue by MrBones757** [EugenMayer/docker-rancher-extra-catalogs#10]
Hello!

Thanks for your amazing work - i'm currently in the middle of trialing your Atlassian docker images to see if they are better than the ones i'm currently using (looks like they are!)
I've been trying to roll out a nexus repository, however i want it to have a persistent volume on an NFS mounted SSD store. I'm using rancher-nfs as my volume plugin. When the container starts, all i get is waiting: container starting. Without the volume driver it works a-okay.

Wondering if you had any insight regarding this issue.
Thanks :)

**Comment by EugenMayer** [comment]
i guess you rather have to give me more insight non your case. So you are using my nexus rancher catalog, right? And you try it to use it with a specific volume drive ( nfs ) and it fails?

**Comment by MrBones757** [comment]
Apologies;
Yes - I'm using your rancher catalog to deploy nexus to a single host/node. My aim is to map the content of nexus-data to a persistent volume on an NFS share using the rancher-nfs volume driver.

To achieve this, I configure the stack using your catalogue item, but uncheck "start services automatically". I then find the service created inside the stack and select "upgrade" to add the required volume driver information. (See attached image)
The error persists regardless of the path name I supply, however when the volume driver field is empty (does not have rancher-nfs present) the container starts as normal.

![image](https://user-images.githubusercontent.com/22608473/37914177-32031236-3149-11e8-9fb8-ec89d35de035.png)

Cheers :)

**Comment by EugenMayer** [comment]
well i guess it would make more sense to support that out of the box using the template language, instead of actually letting you work arround.

We could do things like 

https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/concourse-standalone-worker/3/docker-compose.yml.tpl#L16

https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/concourse-standalone-worker/3/docker-compose.yml.tpl#L48

to have an option in the catalog to select which time of volume driver / volume to use. Are you able to create a PR for this?

**Comment by MrBones757** [comment]
Thanks for your reply
Sorry about my lack of understanding / knowledge here:
I'm slightly confused with what you want me to do - I had a look at a pull request and couldn't see anything that made sense - haven't used the pull request feature of git before.

**Comment by EugenMayer** [comment]
contribute code that basically means, PR is just a different way of contributing a patch. And what i ask you to do is implementing a catalog volume driver switch for your case, so you can use it out of the box

**Comment by MrBones757** [comment]
Ah yep, now that I can definitely attempt to do!
Edit: Will work on it now

**Comment by EugenMayer** [comment]
no worries, any help - any time - is very appritiated

**Comment by MrBones757** [comment]
As requested; I've created a pull request for this with two changes: I've added a dropdown for storage driver, and i've added a field to select the external port. Let me know if this is correct or if you need anything else. (i've not tested this as I was unsure how to) [See Here](https://github.com/EugenMayer/docker-rancher-extra-catalogs/pull/11)

**Comment by EugenMayer** [comment]
timeout
