### ISSUE TITLE
Network storage for traefik certs, conf, etc...

### ISSUE THREAD

**Issue by nitrique** [EugenMayer/docker-rancher-extra-catalogs#13]
Hey Eugen,

I hope you are well,

We had an issue yesterday with traefik and the rancher template, we had an outage on our balancer node's network, so we started a new server to get back online. 

But as the storage is not shared with the rancher template, so we've reached the lets encrypt quota.

Can you had an option on the template to specify the cert directory on docker master so we can use network storage ?

I'll do a pull request for this if you want.

Thanks,
See you round.

Nicolas

**Comment by EugenMayer** [comment]
hey, for sure we can have that, it just needs to be optional, see my other catalogs on how the storage is configureable to a volume or host folder. or are you also talking about a different storage driver?

in any way, for sure interested in adopting this, happy to review a pr

**Comment by nitrique** [comment]
I don't use other storage drivers, but shared storage on main host, because I've didn't find a powerful one on docker

**Comment by EugenMayer** [comment]
sure then check my other catalogs, that's implemented there to understand host mounts and volumes. be sure to add a volume definition in the bottom if a volume mount is used
