### ISSUE TITLE
Is ACME Required?

### ISSUE THREAD

**Issue by cloudlady911** [EugenMayer/docker-rancher-extra-catalogs#16]
Can Traefik pull the certs from Rancher?  If so, what would the settings look like?

**Comment by EugenMayer** [comment]
No traefik handles the certs itself, no exchange with rancher in this regard

**Comment by cloudlady911** [comment]
thanks.  What env variable would I use to tell Acme to use a certificate in a particular folder?

lets say the certs are in a folder on the host called /data/certs/production/domain1 and I mount /data/certs to :/certs

**Comment by cloudlady911** [comment]
I don't want to use ACME.

**Comment by cloudlady911** [comment]
I want this to be added to my traefik.toml file
     [[entryPoints.http.tls.certificates]]
        certFile = "path/to/my.cert"
        keyFile = "path/to/my.key"
      [[entryPoints.http.tls.certificates]]
        certFile = "path/to/other.cert"
        keyFile = "path/to/other.key"

**Comment by EugenMayer** [comment]
See https://github.com/EugenMayer/docker-image-traefik and see the catalog for the mounts, be sure to understand the 1.x and 2.x docs depending on what image / version you plan to use.

 I use traefik with acme only in this env but using concrete certificates should work to

Be sure to read the traefik docs on how certificates are configured
