### ISSUE TITLE
Invalid configuration for PHPLDAPADMIN_HTTPS in test file

### ISSUE THREAD

**Issue by williamdes** [EugenMayer/docker-rancher-extra-catalogs#17]
https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/eae7a0c34790b449307746d38ea73d81c9329264/tests/openldap/docker-compose.yml#L32

```yml
PHPLDAPADMIN_HTTPS: "false"
```

**Comment by EugenMayer** [comment]
Thanks for the hint, fixed. i'am not really using those docker-compose.yml files, so be aware that other things are broken. I only use the real catalog files :)

**Comment by williamdes** [comment]
> Thanks for the hint, fixed. i'am not really using those docker-compose.yml files, so be aware that other things are broken. I only use the real catalog files :)

Thank you for fixing this in 243ade1aaf41dbf065b0e72fa56f33eb728c0b24
Also you could use a newer version like 1.4 :)
I found this file on another repository provided as an example

**Comment by EugenMayer** [comment]
That was just an incubation file - the real/maintained ones are in the catalog, e.g. https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/openldap/24/docker-compose.yml .. those are far better examples due to the variables and docs.
