### ISSUE TITLE
Update a wrong config value for ldap port on tests/openldap/docker-compose.yml

### ISSUE THREAD

**Issue by williamdes** [EugenMayer/docker-rancher-extra-catalogs#18]
https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/243ade1aaf41dbf065b0e72fa56f33eb728c0b24/tests/openldap/docker-compose.yml#L25

Please use port 636 :sob: , I lost so many hours because of this copy pasta (this is not your fault)

Reference comment: https://github.com/osixia/docker-openldap/commit/5384c257c38ffef79643e2219ad35785f7a805e5#commitcomment-44924468

**Comment by EugenMayer** [comment]
As stated, you are using a non maintained, test and incubation part of this repository. This repo is all about rancher catalogs and those are maintained, not that test repo.

To avoid other running into the same issue, i deleted that part from the repository - if you need it, be sure to for this repo and revert it / copy what you need
