### ISSUE TITLE
bitbucket with external database

### ISSUE THREAD

**Issue by sredbull** [EugenMayer/docker-rancher-extra-catalogs#7]
When I create a bitbucket stack with an external database it gives me this error:

Error (Service 'bitbucket' configuration key 'links' contains an invalid type, it should be an array.)  

```
USE_PROXY=true
BITBUCKET_PROXY_NAME=bitbucket.domain.space
BITBUCKET_PROXY_PORT=443
BITBUCKET_PROXY_SCHEME=https
DB_PASSWORD=
BITBUCKET_DB_USER=admin
BITBUCKET_DB_NAME=bitbucketdb
USE_EXTERNAL_DB_SERVICE=true
EXTERNAL_DB_SERVICE=postgres/postgres
```

Double checked the docker-compose and all seems legit. Do you see something edgy? The Jira stacks works perfectly!

**Comment by EugenMayer** [comment]
not sure yet, did you're pr handled this?

**Comment by sredbull** [comment]
It did!
