### ISSUE TITLE
The bamboo template is borked

### ISSUE THREAD

**Issue by sredbull** [EugenMayer/docker-rancher-extra-catalogs#9]
Looks like the Bamboo template is setting bitbucket variables. The template is in the Bitbucket folder making the bitbucket template unusable. I'll try to do a pr later on.

**Comment by EugenMayer** [comment]
there is no bamboo template?

**Comment by EugenMayer** [comment]
i think you mean the bitbucket template and yes, i got fooled by the blackops/bitbucket image, they actually did commit the 5.8 build but did not build it yet, i consider actually forking that one as the other 2. For now, please use one version below 5.8  - sorry for the inconvinience, yet not happened
